### ISSUE TITLE
Can i use this widget in flutter 3.3.3 version?

### ISSUE THREAD

**Issue by Govindbetterlives** [MominRaza/overlay_text_form_field#1]
Hi, Can i use this widget in flutter 3.3.3 version?

Its showing error
overlay_text_form_field >=0.0.2 which requires SDK version >=3.0.0 <4.0.0, version solving failed.

**Comment by MominRaza** [comment]
I think this package doesn't use any dart 3 specific code, so I can decrease the min dart SDK version.

But I suggest you to also update your app to latest flutter version.
